
export const constants = {
    INVALID_VERSION: 'INVALID_VERSION',
    METHOD_NOT_IMPLEMENTED: 'METHOD_NOT_IMPLEMENTED',
    INVALID_PARAMS: 'INVALID_PARAMS',
    INVALID_CONTENT_TYPE: 'INVALID_CONTENT_TYPE',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    BAD_REQUEST: 'BAD_REQUEST',
    DUPLICATE_ENTRY_ERROR_CODE: 'ER_DUP_ENTRY',
};

